#! /usr/bin/env python

import sys
import argparse

from app import commands

p= argparse.ArgumentParser(prog='muxpy', description='manage tmux sessions')
subp = p.add_subparsers(dest='command')

helpp = subp.add_parser('help')
helpp.add_argument('target', help='help on what?')
createp = subp.add_parser('create', description='create a new session')
createp.add_argument('profile', help='the profile name')
startp = subp.add_parser('start', description='start a saved session')

parsed = p.parse_args(sys.argv[1:])
print parsed.command

if parsed.command == 'help':
    args = [parsed.target, '--help']
    p.parse_args(args)
    sys.exit(1)

if parsed.command == 'start':
    commands.start(parsed)
elif parsed.command == 'create':
    commands.create(parsed)

sys.exit(0)
