#! /usr/bin/env python

import argparse
import os
import sys

from app import commands

default_socket = '/tmp/muxpy-%s/default' % os.getuid()
p = argparse.ArgumentParser(description='manage tmux sessions')
p.add_argument('-S', '--socket', default=default_socket, help='the tmux socket. defaults to ' + default_socket)
subp = p.add_subparsers(dest='command')

helpp = subp.add_parser('help')
helpp.add_argument('target', help='help on what?')

createp = subp.add_parser('create', description='create a new session')
createp.add_argument('profile', help='the profile name')
createp.add_argument('--format', '-f', choices=['json'], default='json', help='profile format')

startp = subp.add_parser('start', description='start a saved session')
startp.add_argument('profile', help='the profile name')

parsed = p.parse_args(sys.argv[1:])

if parsed.command == 'help':
    args = [parsed.target, '--help']
    p.parse_args(args)
    sys.exit(1)

if parsed.command == 'start':
    commands.start(parsed)
elif parsed.command == 'create':
    commands.create(parsed)

sys.exit(0)
